// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OgrenciProjesi.Models.Concrete;

namespace OgrenciProjesi.Migrations
{
    [DbContext(typeof(OgrenciProjesiDbContext))]
    partial class OgrenciProjesiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.16");

            modelBuilder.Entity("OgrenciProjesi.Models.Entities.Bolum", b =>
                {
                    b.Property<int>("BolumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BolumAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("BolumBaskani")
                        .HasColumnType("TEXT");

                    b.HasKey("BolumId");

                    b.ToTable("Bolums");
                });

            modelBuilder.Entity("OgrenciProjesi.Models.Entities.Ders", b =>
                {
                    b.Property<int>("DersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DersAdi")
                        .HasColumnType("TEXT");

                    b.Property<string>("DersOgretmeni")
                        .HasColumnType("TEXT");

                    b.Property<string>("Donemi")
                        .HasColumnType("TEXT");

                    b.Property<int>("Kredi")
                        .HasColumnType("INTEGER");

                    b.HasKey("DersId");

                    b.ToTable("Ders");
                });

            modelBuilder.Entity("OgrenciProjesi.Models.Entities.Ogrenci", b =>
                {
                    b.Property<int>("OgrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BolumId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BolumId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DogumTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Donemi")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("OgrenciAd")
                        .HasColumnType("TEXT");

                    b.Property<int>("OgrenciNo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OgrenciSoyad")
                        .HasColumnType("TEXT");

                    b.HasKey("OgrenciId");

                    b.HasIndex("BolumId1");

                    b.ToTable("Ogrencis");
                });

            modelBuilder.Entity("OgrenciProjesi.Models.Entities.OgrenciDers", b =>
                {
                    b.Property<int>("DersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OgrenciId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DersId", "OgrenciId");

                    b.HasIndex("OgrenciId");

                    b.ToTable("OgrenciDers");
                });

            modelBuilder.Entity("OgrenciProjesi.Models.Entities.Ogrenci", b =>
                {
                    b.HasOne("OgrenciProjesi.Models.Entities.Bolum", "Bolum")
                        .WithMany("Ogrencis")
                        .HasForeignKey("BolumId1");

                    b.Navigation("Bolum");
                });

            modelBuilder.Entity("OgrenciProjesi.Models.Entities.OgrenciDers", b =>
                {
                    b.HasOne("OgrenciProjesi.Models.Entities.Ders", "Ders")
                        .WithMany("OgrenciDers")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OgrenciProjesi.Models.Entities.Ogrenci", "Ogrenci")
                        .WithMany("OgrenciDers")
                        .HasForeignKey("OgrenciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Ogrenci");
                });

            modelBuilder.Entity("OgrenciProjesi.Models.Entities.Bolum", b =>
                {
                    b.Navigation("Ogrencis");
                });

            modelBuilder.Entity("OgrenciProjesi.Models.Entities.Ders", b =>
                {
                    b.Navigation("OgrenciDers");
                });

            modelBuilder.Entity("OgrenciProjesi.Models.Entities.Ogrenci", b =>
                {
                    b.Navigation("OgrenciDers");
                });
#pragma warning restore 612, 618
        }
    }
}
